server:
  port: 8081
  shutdown: graceful

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_data?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 6188

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
